version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    #env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reactlibrarydatabase
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: